### ISSUE TITLE
Middleware adapter for http.Handler middleware

### ISSUE THREAD

**Issue by jakenichols2719** [cloudretic/matcha#52]
Lots of other projects use an http.Handler model for middleware, which we don't; I'd like to have an adapter to convert `http.Handler` to `middleware.Middleware`, probably by just running the provided handler inside our middleware signature. An option to reject on some condition after it is run would also be very helpful.

Update May 8 2023: There's a framework in 1.2.0 for this now, but we need to address the way that traditional middleware is constructed. Typically you get a `func (http.Handler) http.Handler`, where the resulting handler passes control to the argument handler on "success". We need to emulate this in our middleware model to ensure that things work as expected.

**Comment by SuneelFreimuth** [comment]
Down to take this

**Comment by jakenichols2719** [comment]
Assigned, thank you!

**Comment by jakenichols2719** [comment]
Moving this from minor to patch. #71 lays out a basic framework for this issue, but there are some unaddressed concerns that are much more involved than should be expected for patch changes. Looking forward at ways to wrap traditional middleware so that it can reject requests by not going to the "next handler".

**Comment by jakenichols2719** [comment]
Yeah... This is part of why I avoided the handler chain pattern. I'm of the opinion that there should be one handler and that should be the end of things, but on the other hand, the `Handler` middleware ecosystem is huge. It's going to be a hard sell to migrate to Matcha if every middleware needs to be rewritten, and I'm personally comfortable obfuscating away a Handler or two to support adoption.

At any rate, I don't have time to work through a solution right now, so it can sit here for a while while we think about it.

**Comment by jakenichols2719** [comment]
Closed from #85
