### ISSUE TITLE
Allow users to specify a fallback route

### ISSUE THREAD

**Issue by SuneelFreimuth** [cloudretic/matcha#63]
Something like
```go
r := router.Declare(
        router.Default(),
        router.WithRoute(...),
        router.WithFallback(<http.Handler>)
)
```
would be useful to explicitly define a no-match behavior.

**Comment by jakenichols2719** [comment]
My first thought is that `router.WithNotFound` is accomplishing this already, as it sets an `http.Handler` that runs whenever none of the registered routes are matched for a request. I'm big on clarifying semantics, but I'm hesitant to duplicate behavior--is there a more specific end goal you're looking for here?

**Comment by SuneelFreimuth** [comment]
No, this addresses it.
