### ISSUE TITLE
Add go report badge

### ISSUE THREAD

**Issue by jakenichols2719** [cloudretic/matcha#65]
Our go report [here](https://goreportcard.com/report/github.com/cloudretic/matcha) looks pretty good, so we should get that badge in ASAP.

**Comment by ravsii** [comment]
Hi, I'm new to the repo, but I can submit a pull request if you would like me to. I found this repository through the "good first issue" label.

_Also, the Go report card did catch some errors_

**Comment by jakenichols2719** [comment]
Yeah... I've been trying really hard to not think about the fact that I misspelled "propagate" *three times*. Whoops.

Issue assigned, we're happy to have you! If you would like to fix those spelling and assignment errors, that would be greatly appreciated. It looks like they're all either in tests or non-exported code, so it shouldn't be a breaking-the-api issue to do so.

**Comment by ravsii** [comment]
Happens, lol.
@jakenichols2719 is it ok if I submit badge and fixes as 1 PR?

**Comment by jakenichols2719** [comment]
That would be great, thank you! ☺️

**Comment by jakenichols2719** [comment]
Closed by #68, thank you @ravsii!
